chaintech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls'))
]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='HomePage'),
    path('user/profile-info/', views.ProfileInfoView, name='ProfilePage'),
    path('user/post/create/', views.CreatePostView.as_view(), name='CreatePost'),
    path('auth/register/', views.RegisterView.as_view(), name='register'),
    path('auth/profile/<int:pk>', views.ProfileView.as_view(), name='Profile'),
    path("auth/login/",auth_views.LoginView.as_view(template_name='dashboard/login.html'),name="login"),
    path("auth/logout/",auth_views.LogoutView.as_view(),name="logout"),
]

dashboard/models.py
from django.db import models
from django.utils import timezone
from django.contrib import auth
from django.contrib.auth.models import User as MainUser

# Create your models here.

class Register(auth.models.User,auth.models.PermissionsMixin):
    def __str__(self):
        return f"@{self.username}"


class Profile(models.Model):
    owner = models.ForeignKey(MainUser, related_name='UserProfile', on_delete=models.CASCADE, unique=True)
    profile_picture = models.FileField(upload_to='media', blank=True, null=True)
    bio = models.TextField(blank=True, null=True)


class HomePage(models.Model):
    owner = models.ForeignKey(MainUser, on_delete=models.CASCADE, related_name='HomePage')
    title = models.CharField(max_length=255)
    pic = models.FileField(upload_to='media', blank=True, null=True)
    uploaded_at = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return str(self.title)[:15]

dashboard/forms.py
from django import forms
from dashboard.models import Register, Profile, HomePage

class RegistrationForm(forms.ModelForm):
    class Meta:
        model = Register
        fields = ['username', 'email', 'password', 'first_name', 'last_name', ]

        widgets = {
            'username': forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':'user123',
            }),
            'email':forms.EmailInput(attrs={
                'class':'form-control',
                'placeholder':'user123@example.com'
            }),
            'password': forms.PasswordInput(attrs={
                'class':'form-control',
            }),
            'first_name': forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':'First Name',
            }),
            'last_name': forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':'Last Name'
            })
        }


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_picture', 'bio' ]
        widgets = {
            'profile_picture': forms.FileInput(attrs={
                'class': 'form-control',
            }),
            'bio': forms.Textarea(attrs={
                'rows':2,
                'class':'form-control'
            })
        }


class HomePageForm(forms.ModelForm):
    class Meta:
        model = HomePage
        fields = ['title', 'pic', ]

        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder':'Post Title',
            }),

            'pic': forms.FileInput(attrs={
                'class': 'form-control',
            })
        }

dashboard/views.py
from typing import Any
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from dashboard.models import HomePage, Register, Profile
from dashboard.forms import RegistrationForm, ProfileForm, HomePageForm

# Create your views here.

class HomePageView(ListView):
    model = HomePage
    template_name = 'dashboard/home.html'


class RegisterView(CreateView):
    model = Register
    template_name = 'dashboard/register.html'
    form_class = RegistrationForm

    def get_success_url(self):
        return reverse('dashboard:Profile', kwargs={'pk' :self.object.pk})


class ProfileView(CreateView):
    model = Profile
    template_name = 'dashboard/profile.html'
    form_class = ProfileForm

    def post(self, request, pk):
        data = ProfileForm(request.POST, request.FILES)
        user = get_user_model().objects.filter(pk=pk).first()
        if data.is_valid():
            user_data = data.save(commit=False)
            user_data.owner = user
            user_data.save()
        return redirect(reverse('dashboard:HomePage'))

@login_required()
def ProfileInfoView(request):
    user = request.user
    user_data = get_user_model().objects.get(pk=user.pk)
    profile_data = Profile.objects.get(owner=user)
    return render(request, 'dashboard/profile-info.html', context={'user':user_data, 'profile_data':profile_data})


class CreatePostView(LoginRequiredMixin, CreateView):
    model = HomePage
    form_class = HomePageForm
    template_name = 'dashboard/post.html'

    def post(self, request):
        user = request.user
        data = HomePageForm(request.POST, request.FILES)
        if data.is_valid():
            user_data = data.save(commit=False)
            user_data.owner = user
            user_data.save()
        return redirect(reverse('dashboard:HomePage'))

dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>
</head>

<body style="margin: 0; font-family: 'Times New Roman', Times, serif;">
    <header>
        <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
            <div class="container-fluid">
              <a class="navbar-brand fs-4" href="{% url 'dashboard:HomePage' %}">ChainTech</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link fs-5 {% block HomeActive %}{% endblock %}" aria-current="page" href="{% url 'dashboard:HomePage' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link fs-5 {% block PostActive %}{% endblock %}" aria-current="page" href="{% url 'dashboard:CreatePost' %}">Create Post</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link fs-5 {% block ProfileActive %}{% endblock %}" aria-current="page" href="{% url 'dashboard:ProfilePage' %}">Profile</a>
                  </li>
                </ul>
                <div class="d-flex me-5">
                  {% if user.is_authenticated %}
                  <form method="post" action="{% url 'dashboard:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-danger px-4">Logout</button>
                  </form>
                  {% else %}
                    <a href="{% url 'dashboard:register' %}" class="btn btn-outline-warning me-5 px-4"> Register</a>
                    <a href="{% url 'dashboard:login' %}" class="btn btn-outline-success me-5 px-4"> LogIn</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </nav>
    </header>
    {% block body %}{% endblock %}
    <footer style="text-align: center; background-color: black; color: white; margin: 0;">
        <div class="row text-center pt-3">
          <div class="col-md-2"></div>
          <div class="col-md-3" style="max-width: 15em;">
            Created by Rahul Bandi <br>
            Contact : +91 93981 49614 <br>
            Email : <a href="mailto:rahulsmrd@gmial.com" target='_blank'>rahulsmrd@gmail.com</a>
          </div>
          <div class="col-md-4 ms-5 ps-5" style="max-width: 15em;">
            Address : <br>
            14-55-89/888, US Street, <br>
            New York, 589656
          </div>
          <div class="col-md-2"></div>
          <div class="col-md-2 ms-5 ps-5">
            <a href="#" class="fs-3 me-3"><i class="bi bi-linkedin"></i></a>
            <a href="#" class="fs-3 me-3"><i class="bi bi-github"></i></a>
            <a href="#" class="fs-3 me-3"><i class="bi bi-instagram"></i></a>
          </div>
        </div>
        <br><br>
        All copyrights received 2024 &copy
    </footer>
</body>

</html>

dashboard/templates/dashboard/home.html
{% extends "dashboard/base.html" %}

{% block title %}Home{% endblock %}
{% block HomeActive %}active{% endblock %}

{% block body %}

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        {% for post in homepage_list %}

        <div class="card m-3">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4">
                        @{{ post.owner }}
                    </div>
                    <div class="col-md-3"></div>
                    <div class="col-md-5" style="color:darkgray;">
                        Uploaded:{{ post.uploaded_at | date:"d M,Y h:i A" }}
                    </div>
                </div><hr>
                <div class="text-center">
                    <img src="{{ post.pic.url }}" alt="postPic" style="max-width: 20em;">
                </div>
                <hr>
                <h4 class="text-center">{{ post.title }}</h4>

            </div>
        </div>

        {% endfor %}
    </div>
</div>



{% endblock %}

dashboard/templates/dashboard/login.html
{% extends 'dashboard/base.html' %}

{% block title %}LogIn{% endblock %}

{% block body %}

<p style="color: red;">
    {{ form.errors }}
</p>

<h1 class="text-center mb-4"><b><u> Please Log In !!!</u></b></h1>
<form method="post">
    {% csrf_token %}
    <div class="text-center my-5">
        <h4>{{ form.username.label }} :</h4> {{ form.username }} <br><br>
        <h4>{{ form.password.label }} :</h4> {{ form.password }} <br><br>
        <button type="submit" class="btn btn-outline-success form-control fs-5" style="max-width: 10em;">Submit</button>
    </div>
</form>

{% endblock %}

dashboard/templates/dashboard/post.html
{% extends 'dashboard/base.html' %}
{% block PostActive %}active{% endblock %}
{% block title %}Posts{% endblock %}

{% block body %}

<p style="color: red;">{{ form.errors }}</p>
<h1 class="text-center my-3">
    Create a Post !!!
</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-6">
                    <h5><b>{{form.title.label}}</b> :</h5> {{ form.title }}
                </div>
                <div class="col-md-6">
                    <h5><b>{{form.pic.label}}</b> :</h5> {{ form.pic }}
                </div>
            </div>
        </div>
        <div class="text-center my-5">
            <button class=" btn btn-outline-success px-5 fs-5" type="submit">Post</button>
        </div>
    </div>
</form>

{% endblock %}

dashboard/templates/dashboard/profile-info.html
{% extends 'dashboard/base.html' %}

{% block title %}User Profile{% endblock %}

{% block ProfileActive %}active{% endblock %}
{% block body %}

<h1 class="text-center my-3">Profile Information !!!</h1>
<div class="row mt-5">
    <div class="col-md-1"></div>
    <div class="col-md-5">
        <div class="card mb-2" style="background-color: azure; border: 2px solid black;">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <label for="username" class="fs-5"><b>Username :</b></label>
                        <input type="text" id="username" readonly class="form-control" value="{{ user.username }}" style="max-width: 20em;">
                    </div>
                    <div class="col-md-6">
                        <label for="email" class="fs-5"><b>Email :</b></label>
                        <input type="text" id="email" readonly class="form-control" value="{{ user.email }}" style="max-width: 20em;">
                    </div>
                </div><br>
                <div class="row">
                    <div class="col-md-6">
                        <label for="first_name" class="fs-5"><b>First Name :</b></label>
                        <input type="text" id="first_name" readonly class="form-control" value="{{ user.first_name }}" style="max-width: 20em;">
                    </div>
                    <div class="col-md-6">
                        <label for="last_name" class="fs-5"><b>Last Name :</b></label>
                        <input type="text" id="last_name" readonly class="form-control" value="{{ user.last_name }}" style="max-width: 20em;">
                    </div>
                </div><br>
                <label for="Bio" class="fs-5"><b>Bio :</b></label>
                <textarea type="text" id="Bio" readonly class="form-control" style="max-width: 20em;">{{ profile_data.bio }}</textarea>
            </div>
        </div>

    </div>
    <div class="col-md-5">
        {% if profile_data.profile_picture %}
        <img src="{{profile_data.profile_picture.url}}" alt="" style="max-width: 40em; border-radius: 1em;">
        {% else %}
        <p>No Image Added ...</p>
        {% endif %}
    </div>
</div>

{% endblock %}

dashboard/templates/dashboard/profile.html
{% extends 'dashboard/base.html' %}
{% block title %}Update Profile Details{% endblock %}

{% block body %}

<p style="color: red;">
    {{ form.errors }}
</p>

<h1 class="text-center my-4">
    <u>Update Your Profile Details</u>
</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row my-3">
        <div class="col-md-4"></div>
        <div class="col-md-5">
            <h5><b>{{ form.profile_picture.label }} :</b> {{ form.profile_picture }}</h5>
            <h5><b>{{ form.bio.label }} :</b></h5>{{ form.bio }} <br>
            <button type="submit" class="btn btn-outline-success px-4 fs-5">Submit</button>
        </div>
    </div>
</form>

{% endblock %}

dashboard/templates/dashboard/register.html
{% extends 'dashboard/base.html' %}
{% block title %}Register{% endblock %}

{% block body %}

<p style="color: red;">
    {{ form.errors }}
</p>

<h1 class="text-center my-3">
    Register Here !!!
</h1>
<form method="post">
    {% csrf_token %}
    <div class="row mt-5">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-6">
                    <h4><b>{{ form.username.label }} :</b></h4>{{form.username}} <br>
                    <p>{{ form.username.help_text }}</p>
                </div>
                <div class="col-md-6">
                    <h4><b>{{ form.email.label }} :</b></h4>{{form.email}} <br>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <h4><b>{{ form.password.label }} :</b></h4>{{form.password}} <br>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <h4><b>{{ form.first_name.label }} :</b></h4>{{form.first_name}} <br>
                </div>
                <div class="col-md-6">
                    <h4><b>{{ form.last_name.label }} :</b></h4>{{form.last_name}} <br>
                </div>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-outline-success form-control fs-5 mb-3" style="max-width: 8em;">Submit</button>
            </div>
        </div>
    </div>
</form>

{% endblock %}